apiVersion: v1
kind: Service
metadata:
  name: biscsm-app
  labels:
    app: biscsm-app
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: biscsm-app